# action.yml
name: 'Hey From a GitHub Action'
on: push
description: 'Greet someone'
inputs:
  user:  # id of input
    description: 'Who to greet'
    required: true
    default: 'You'
runs:
  using: "composite"
  steps: 
    - run: echo Hey ${{ inputs.user }}.
      shell: bash